//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeakDanish.Resources.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpeakDanish.Resources.Translations.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Recording ({0} seconds).
        /// </summary>
        public static string Home_MyRecordingWithSeconds {
            get {
                return ResourceManager.GetString("Home_MyRecordingWithSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordings.
        /// </summary>
        public static string Home_Recordings {
            get {
                return ResourceManager.GetString("Home_Recordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recording ({0} seconds).
        /// </summary>
        public static string Home_RecordingsWithSeconds {
            get {
                return ResourceManager.GetString("Home_RecordingsWithSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Recording.
        /// </summary>
        public static string Home_SaveRecording {
            get {
                return ResourceManager.GetString("Home_SaveRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speak this sentence.
        /// </summary>
        public static string Home_SpeakThisSentence {
            get {
                return ResourceManager.GetString("Home_SpeakThisSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transcribing ({0} seconds).
        /// </summary>
        public static string Home_TranscribeWithSeconds {
            get {
                return ResourceManager.GetString("Home_TranscribeWithSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Recording.
        /// </summary>
        public static string Home_YourRecording {
            get {
                return ResourceManager.GetString("Home_YourRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Transcription.
        /// </summary>
        public static string Home_YourTranscription {
            get {
                return ResourceManager.GetString("Home_YourTranscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Recording_Delete {
            get {
                return ResourceManager.GetString("Recording_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recordings.
        /// </summary>
        public static string Recording_Title {
            get {
                return ResourceManager.GetString("Recording_Title", resourceCulture);
            }
        }
    }
}
