//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeakDanish.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   This class was generated by MSBuild using the GenerateResource task.
    ///   To add or remove a member, edit your .resx file then rerun MSBuild.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Build.Tasks.StronglyTypedResourceBuilder", "15.1.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_da {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_da() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpeakDanish.Resources.AppResources.da", typeof(AppResources_da).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min optagelse ({0} sekunder).
        /// </summary>
        internal static string Home_MyRecordingWithSeconds {
            get {
                return ResourceManager.GetString("Home_MyRecordingWithSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optagelser.
        /// </summary>
        internal static string Home_Recordings {
            get {
                return ResourceManager.GetString("Home_Recordings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gem optagelse.
        /// </summary>
        internal static string Home_SaveRecording {
            get {
                return ResourceManager.GetString("Home_SaveRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tal denne sætning.
        /// </summary>
        internal static string Home_SpeakThisSentence {
            get {
                return ResourceManager.GetString("Home_SpeakThisSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hjem.
        /// </summary>
        internal static string Home_Title {
            get {
                return ResourceManager.GetString("Home_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Din optagelse.
        /// </summary>
        internal static string Home_YourRecording {
            get {
                return ResourceManager.GetString("Home_YourRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slet.
        /// </summary>
        internal static string Recording_Delete {
            get {
                return ResourceManager.GetString("Recording_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optagelser.
        /// </summary>
        internal static string Recording_Title {
            get {
                return ResourceManager.GetString("Recording_Title", resourceCulture);
            }
        }
    }
}
